#ifndef FE_OBJECT4_H
#define FE_OBJECT4_H

#include "common.h"
#include "field.h"

extern void func_800ADB68(u8 *buf, s32 arg);
extern void func_800ADC04(void);
extern s32  opHandler_NOP(Eline *e);
extern void opHandler_ADD(Eline *e);
extern void opHandler_SUB(Eline *e);
extern void opHandler_NEG(Eline *e);
extern void opHandler_MUL(Eline *e);
extern void opHandler_DIV(Eline *e);
extern void opHandler_MOD(Eline *e);
extern void opHandler_EQ(Eline *e);
extern void opHandler_GT(Eline *e);
extern void opHandler_GE(Eline *e);
extern void opHandler_LT(Eline *e);
extern void opHandler_LE(Eline *e);
extern void opHandler_NE(Eline *e);
extern void opHandler_AND(Eline *e);
extern void opHandler_OR(Eline *e);
extern void opHandler_EOR(Eline *e);
extern void opHandler_NOT(Eline *e);
extern void opHandler_RSH(Eline *e);
extern void opHandler_LSH(Eline *e);
extern s32  opHandler_CAL(Eline *e, s32 opcode);
extern s32  opHandler_JMP(Eline *e, s32 a1);
extern s32  opHandler_JPF(Eline *e, s32 a1);
extern s32  opHandler_GJMP(Eline *e, s32 a1);
extern s32  opHandler_LBL(Eline *e, s32 a1);
extern void func_800AE184(Eline *e);
extern s32  opHandler_RET(Eline *e, s32 a1);
extern s32  func_800AE3A4(s32 value, s32 mode);
extern s32  opHandler_PSHN_L(Eline *e, s32 a1);
extern s32  opHandler_PSHI_L(Eline *e, s32 a1);
extern s32  opHandler_PSHM_B(Eline *e, s32 a1);
extern s32  opHandler_PSHM_W(Eline *e, s32 a1);
extern s32  opHandler_PSHM_L(Eline *e, s32 a1);
extern s32  opHandler_PSHSM_B(Eline *e, s32 a1);
extern s32  opHandler_PSHSM_W(Eline *e, s32 a1);
extern s32  opHandler_PSHSM_L(Eline *e, s32 a1);
extern s32  opHandler_POPI_L(Eline *e, s32 a1);
extern s32  opHandler_POPM_B(Eline *e, s32 a1);
extern s32  opHandler_POPM_W(Eline *e, s32 a1);
extern s32  opHandler_POPM_L(Eline *e, s32 a1);
extern s32  opHandler_PSHAC(Eline *e, s32 a1);
extern s32  func_800AE8B4(Eline *e, u8 newGroup, u16 pcIdx);
extern s32  opHandler_REQ(Eline *e, s32 a1);
extern s32  opHandler_REQSW(Eline *e, s32 a1);
extern s32  opHandler_REQEW(Eline *e, s32 a1);
extern s32  opHandler_PREQ(Eline *e, s32 a1);
extern s32  opHandler_PREQSW(Eline *e, s32 a1);
extern s32  opHandler_PREQEW(Eline *e, s32 a1);
extern s32  opHandler_DEBUG(Eline *e);
extern s32  opHandler_HALT(Eline *e);
extern s32  opHandler_SET(Eline *e, s32 a1);
extern s32  opHandler_SET3(Eline *e, s32 a1);
extern s32  opHandler_IDLOCK(Eline *e, s32 bit);
extern s32  opHandler_IDUNLOCK(Eline *e, s32 bit);
extern s32  opHandler_WAIT(Eline *e);
extern s32  opHandler_CLEAR(void);
extern s32  opHandler_RND(FieldEntity *entity);
extern s32  opHandler_SETMODEL(Eline *e, s32 a1);
extern s32  func_800AF120(Eline *e);
extern s32  func_800AF1AC(Eline *e);
extern s32  opHandler_BASEANIME(Eline *e, s32 a1);
extern s32  opHandler_LADDERANIME(Eline *e, s32 a1);
extern s32  opHandler_KEYSCAN(Eline *e);
extern s32  opHandler_KEYON(Eline *e);
extern s32  func_800AF364(Eline *e);
extern s32  func_800AF3B4(Eline *e);
extern s32  opHandler_SARALYOFF(Eline *e);
extern s32  opHandler_SARALYON();
extern s32  opHandler_SARALYDISPOFF(void);
extern s32  opHandler_SARALYDISPON(void);
extern s32  opHandler_SETLINE(Eline *e);
extern s32  opHandler_LINEON(Eline *e);
extern s32  opHandler_LINEOFF(Eline *e);
extern s32  func_800AF5C4(Eline *e);
extern s32  func_800AF5D4(Eline *e);
extern s32  opHandler_USE(Eline *e);
extern s32  opHandler_UNUSE(Eline *e);
extern s32  opHandler_UCON(void);
extern s32  opHandler_UCOFF(void);
extern s32  func_800AFD20(Eline *e);
extern s32  opHandler_SETPC(Eline *e);
extern s32  opHandler_ADDPARTY(Eline *e);
extern s32  opHandler_SUBPARTY(Eline *e);
extern s32  func_800B002C(Eline *e);
extern s32  opHandler_SETPARTY(Eline *e);
extern s32  func_800B0280(Eline *e);
extern s32  opHandler_ISPARTY(Eline *e);
extern s32  opHandler_GETPARTY(Eline *e);
extern s32  opHandler_ADDMEMBER(Eline *e);
extern s32  opHandler_SUBMEMBER(Eline *e);
extern s32  func_800B0570(Eline *e);
extern s32  func_800B0638(Eline *e, s32 a1);
extern s32  func_800B06D0(Eline *e);
extern s32  opHandler_LASTIN(Eline *e, s32 a1);
extern s32  opHandler_LASTOUT(Eline *e);

#endif
