name: field.bin
sha1: 1787bc2d0ee08f2e0a29b78bd0f07a0bbcfe2bc8
options:
  basename: field
  target_path: original/field.bin
  elf_path: build/field/field.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/field
  src_path: src/field
  build_path: build/field

  # Linker
  ld_script_path: config/field.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.field.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.field.txt
  undefined_syms_auto_path: config/undefined_syms_auto.field.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: field
    type: code
    start: 0x0
    vram: 0x80098000
    subsegments:
      - [0x0, rodata]
      - [0x8, .rodata, fe_object1]
      - [0x20, rodata]
      - [0x1C4, .rodata, fe_object6]
      - [0x218, rodata]
      - [0x21C, .rodata, fe_object7]
      - [0x23C, rodata]
      - [0x314, c, fe_object1]
      - [0x14B10, c, fe_object2]
      - [0x157AC, c, fe_object3]
      - [0x15B68, c, fe_object4]
      - [0x1885C, c, fe_object5]
      - [0x1A348, c, fe_object6]
      - [0x1D42C, c, fe_object7]
      - [0x21078, c, fe_object8]
      - [0x232A4, c, fe_object9]
      - [0x251F4, c, fe_object10]
      - [0x275D4, c, fe_object11]
      - [0x28098, c, fe_object12]
      - [0x286A0, data, fe_object12_data]
      - [0x2B898, bin]
  - [0x2ED80]
