name: intro.bin
sha1: f56613c381e68076b3da62c84574444c9d672a4e
options:
  basename: intro
  target_path: original/intro.bin
  elf_path: build/ovl/intro/intro.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/intro
  src_path: src
  build_path: build/ovl/intro

  # Linker
  ld_script_path: config/intro.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.intro.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.intro.txt
  undefined_syms_auto_path: config/undefined_syms_auto.intro.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: intro
    type: code
    start: 0x0
    vram: 0x80098000
    subsegments:
      - [0x0, c, intro]
      - [0x10B8, .data, intro_assets]
      - [0x11D8, data]
  - [0x12B0]
