name: menumgc.ovl
sha1: 967125cc95317880d0c2e0d0f61f66a62c21125f
options:
  basename: menumgc
  target_path: original/menumgc.ovl
  elf_path: build/ovl/menumgc/menumgc.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menumgc
  src_path: src/menu/menumgc
  build_path: build/ovl/menumgc

  # Linker
  ld_script_path: config/menumgc.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menumgc.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menumgc.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menumgc.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menumgc
    type: code
    start: 0x0
    vram: 0x801E5800
    subsegments:
      - [0x0, c, menumgc]
      - [0x6E28, rodata]
  - [0x71F0]
