name: menushop.ovl
sha1: b968bdd8b9335ffa5e998ea8ef985cfc1863c2db
options:
  basename: menushop
  target_path: original/menushop.ovl
  elf_path: build/ovl/menushop/menushop.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menushop
  src_path: src/menu/menushop
  build_path: build/ovl/menushop

  # Linker
  ld_script_path: config/menushop.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menushop.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menushop.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menushop.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menushop
    type: code
    start: 0x0
    vram: 0x801E5800
    subsegments:
      - [0x0, c, menushop]
      - [0x429C, rodata]
      - [0x4570, data]
  - [0x5228]
