name: menupty.ovl
sha1: 17736cb92c8cb34e651e01ba01285b7a1a895159
options:
  basename: menupty
  target_path: original/menupty.ovl
  elf_path: build/ovl/menupty/menupty.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menupty
  src_path: src/menu/menupty
  build_path: build/ovl/menupty

  # Linker
  ld_script_path: config/menupty.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menupty.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menupty.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menupty.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menupty
    type: code
    start: 0x0
    vram: 0x801E5800
    subsegments:
      - [0x0, c, menupty]
      - [0x3C7C, rodata]
  - [0x3D40]
