name: menutips.ovl
sha1: 0659afebe53fc060592eda101ec59bfac6997faa
options:
  basename: menutips
  target_path: original/menutips.ovl
  elf_path: build/ovl/menutips/menutips.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menutips
  src_path: src/menu/menutips
  build_path: build/ovl/menutips

  # Linker
  ld_script_path: config/menutips.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menutips.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menutips.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menutips.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menutips
    type: code
    start: 0x0
    vram: 0x801E5800
    subsegments:
      - [0x0, c, menutips]
      - [0x1268, rodata]
  - [0x1310]
