name: menuitem.ovl
sha1: a54f1c5ba8982d20e7a63287f632652a44a2a9b4
options:
  basename: menuitem
  target_path: original/menuitem.ovl
  elf_path: build/ovl/menuitem/menuitem.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menuitem
  src_path: src/menu/menuitem
  build_path: build/ovl/menuitem

  # Linker
  ld_script_path: config/menuitem.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menuitem.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menuitem.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menuitem.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menuitem
    type: code
    start: 0x0
    vram: 0x801E2800
    subsegments:
      - [0x0, c, menuitem]
      - [0x8654, rodata]
      - [0x9F1C, data]
  - [0xA320]
