name: menutmag.ovl
sha1: 9c3467b1cc10db163e33c7657bc7681850e9c243
options:
  basename: menutmag
  target_path: original/menutmag.ovl
  elf_path: build/ovl/menutmag/menutmag.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menutmag
  src_path: src/menu/menutmag
  build_path: build/ovl/menutmag

  # Linker
  ld_script_path: config/menutmag.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menutmag.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menutmag.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menutmag.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menutmag
    type: code
    start: 0x0
    vram: 0x801E5800
    subsegments:
      - [0x0, c, menutmag]
      - [0xBA8, rodata]
  - [0x1E4C]
