name: menusts.ovl
sha1: 113a79248329389c58a8b9174cefe914ae198a57
options:
  basename: menusts
  target_path: original/menusts.ovl
  elf_path: build/ovl/menusts/menusts.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/menusts
  src_path: src/menu/menusts
  build_path: build/ovl/menusts

  # Linker
  ld_script_path: config/menusts.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.menusts.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.menusts.txt
  undefined_syms_auto_path: config/undefined_syms_auto.menusts.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: menusts
    type: code
    start: 0x0
    vram: 0x801E5800
    subsegments:
      - [0x0, c, menusts]
      - [0x3CC8, rodata]
      - [0x42E4, data]
  - [0x46E4]
