name: tripletriad.bin
sha1: accfe3831595f26c5d6de6f3891736521736f8ef
options:
  basename: tripletriad
  target_path: original/tripletriad.bin
  elf_path: build/ovl/tripletriad/tripletriad.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/tripletriad
  src_path: src/tripletriad
  build_path: build/ovl/tripletriad

  # Linker
  ld_script_path: config/tripletriad.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.tripletriad.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.tripletriad.txt
  undefined_syms_auto_path: config/undefined_syms_auto.tripletriad.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data", ".bss"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: tripletriad
    type: code
    start: 0x0
    vram: 0x80098000
    subsegments:
      - { start: 0x0, type: .rodata, name: be_object1, linker_section_order: .text }
      - [0xDC, asm, be_dispatch]
      - { start: 0x104, type: .rodata, name: be_object2, linker_section_order: .text }
      - [0x154, asm, be_dispatch_mid]
      - { start: 0x164, type: .rodata, name: be_object3, linker_section_order: .text }
      - { start: 0x178, type: data, name: be_dispatch_post, linker_section_order: .text }
      - [0x22C, c, be_object1]
      - [0x28CC, c, be_object2]
      - [0x6248, c, be_object3]
      - [0x9BE0, c, be_object4]
      - [0xC58C, asm, be_data]             # data tables: jump tables, animation data, etc. (not code)
  - [0x10AC40]
