/* Field script-VM opcode dispatch table at 0x800C6760.
 *
 * Layout (392 function pointers = 0x620 bytes):
 *
 *   Indices 0x000-0x011 (18 entries) — stack arithmetic sub-table.
 *     Invoked via the CAL opcode (op001 @ table index 0x013), which is
 *     @c opHandler_CAL. CAL reads a sub-opcode in @c a1 and tail-calls
 *     @c g_fieldOpcodeTable[a1]. The 18 entries are pure stack ops on
 *     the eline's value stack at offset 0x184: ADD, SUB, MUL, DIV, MOD,
 *     NEG, EQ, GT, GE, LT, LE, NE, AND, OR, EOR, NOT, RSH, LSH.
 *
 *   Indices 0x012-0x187 (374 entries) — main field-VM opcode dispatch.
 *     The runtime dispatcher (fe_object10 func_800BEBD0/func_800BD9C4)
 *     reads packed bytecode words (@c func_80037B7C extracts the
 *     high byte as the opcode and sign-extends the lower 24 bits as
 *     the arg) and indexes @c g_fieldOpcodeTable + 0x48 (i.e. our 0x012) by
 *     @c opcode * 4. So wiki opcode N (0x000-0x175) corresponds to
 *     our table index N + 0x12.
 *
 * Wiki opcode names below come from
 * https://hobbitdur.github.io/FF8ModdingWiki/technical-reference/field/field-opcodes/.
 * Entries marked "???" are not documented on the wiki.
 */
#include "common.h"
#include "field.h"
#include "field/fe_object1.h"
#include "field/fe_object2.h"
#include "field/fe_object3.h"
#include "field/fe_object4.h"
#include "field/fe_object5.h"
#include "field/fe_object6.h"
#include "field/fe_object7.h"
#include "field/fe_object8.h"
#include "field/fe_object9.h"
#include "field/fe_object10.h"
#include "field/fe_object11.h"
#include "field/fe_object12.h"

/* Forward declarations for the 392 opcode handlers (K&R-style
 * unprototyped — the table cast handles arg-type compatibility). */

typedef s32 (*OpcodeFn)();

s32 (*g_fieldOpcodeTable[392])() = {
    /* 0x000  arith ADD              */ (OpcodeFn)opHandler_ADD,
    /* 0x001  arith SUB              */ (OpcodeFn)opHandler_SUB,
    /* 0x002  arith MUL              */ (OpcodeFn)opHandler_MUL,
    /* 0x003  arith DIV              */ (OpcodeFn)opHandler_DIV,
    /* 0x004  arith MOD              */ (OpcodeFn)opHandler_MOD,
    /* 0x005  arith NEG              */ (OpcodeFn)opHandler_NEG,
    /* 0x006  arith EQ               */ (OpcodeFn)opHandler_EQ,
    /* 0x007  arith GT               */ (OpcodeFn)opHandler_GT,
    /* 0x008  arith GE               */ (OpcodeFn)opHandler_GE,
    /* 0x009  arith LT               */ (OpcodeFn)opHandler_LT,
    /* 0x00A  arith LE               */ (OpcodeFn)opHandler_LE,
    /* 0x00B  arith NE               */ (OpcodeFn)opHandler_NE,
    /* 0x00C  arith AND              */ (OpcodeFn)opHandler_AND,
    /* 0x00D  arith OR               */ (OpcodeFn)opHandler_OR,
    /* 0x00E  arith EOR              */ (OpcodeFn)opHandler_EOR,
    /* 0x00F  arith NOT              */ (OpcodeFn)opHandler_NOT,
    /* 0x010  arith RSH              */ (OpcodeFn)opHandler_RSH,
    /* 0x011  arith LSH              */ (OpcodeFn)opHandler_LSH,
    /* 0x012  op000  NOP             */ (OpcodeFn)opHandler_NOP,
    /* 0x013  op001  CAL             */ (OpcodeFn)opHandler_CAL,
    /* 0x014  op002  JMP             */ (OpcodeFn)opHandler_JMP,
    /* 0x015  op003  JPF             */ (OpcodeFn)opHandler_JPF,
    /* 0x016  op004  GJMP           */ (OpcodeFn)opHandler_GJMP,
    /* 0x017  op005  LBL             */ (OpcodeFn)opHandler_LBL,
    /* 0x018  op006  RET             */ (OpcodeFn)opHandler_RET,
    /* 0x019  op007  PSHN_L          */ (OpcodeFn)opHandler_PSHN_L,
    /* 0x01A  op008  PSHI_L          */ (OpcodeFn)opHandler_PSHI_L,
    /* 0x01B  op009  POPI_L          */ (OpcodeFn)opHandler_POPI_L,
    /* 0x01C  op00A  PSHM_B          */ (OpcodeFn)opHandler_PSHM_B,
    /* 0x01D  op00B  POPM_B          */ (OpcodeFn)opHandler_POPM_B,
    /* 0x01E  op00C  PSHM_W          */ (OpcodeFn)opHandler_PSHM_W,
    /* 0x01F  op00D  POPM_W          */ (OpcodeFn)opHandler_POPM_W,
    /* 0x020  op00E  PSHM_L          */ (OpcodeFn)opHandler_PSHM_L,
    /* 0x021  op00F  POPM_L          */ (OpcodeFn)opHandler_POPM_L,
    /* 0x022  op010  PSHSM_B         */ (OpcodeFn)opHandler_PSHSM_B,
    /* 0x023  op011  PSHSM_W         */ (OpcodeFn)opHandler_PSHSM_W,
    /* 0x024  op012  PSHSM_L         */ (OpcodeFn)opHandler_PSHSM_L,
    /* 0x025  op013  PSHAC           */ (OpcodeFn)opHandler_PSHAC,
    /* 0x026  op014  REQ             */ (OpcodeFn)opHandler_REQ,
    /* 0x027  op015  REQSW           */ (OpcodeFn)opHandler_REQSW,
    /* 0x028  op016  REQEW           */ (OpcodeFn)opHandler_REQEW,
    /* 0x029  op017  PREQ            */ (OpcodeFn)opHandler_PREQ,
    /* 0x02A  op018  PREQSW          */ (OpcodeFn)opHandler_PREQSW,
    /* 0x02B  op019  PREQEW          */ (OpcodeFn)opHandler_PREQEW,
    /* 0x02C  op01A  UNUSE           */ (OpcodeFn)opHandler_UNUSE,
    /* 0x02D  op01B  DEBUG           */ (OpcodeFn)opHandler_DEBUG,
    /* 0x02E  op01C  HALT            */ (OpcodeFn)opHandler_HALT,
    /* 0x02F  op01D  SET             */ (OpcodeFn)opHandler_SET,
    /* 0x030  op01E  SET3            */ (OpcodeFn)opHandler_SET3,
    /* 0x031  op01F  IDLOCK          */ (OpcodeFn)opHandler_IDLOCK,
    /* 0x032  op020  IDUNLOCK        */ (OpcodeFn)opHandler_IDUNLOCK,
    /* 0x033  op021  EFFECTPLAY2     */ (OpcodeFn)opHandler_EFFECTPLAY2,
    /* 0x034  op022  FOOTSTEP        */ (OpcodeFn)opHandler_FOOTSTEP,
    /* 0x035  op023  JUMP            */ (OpcodeFn)opHandler_JUMP,
    /* 0x036  op024  JUMP3           */ (OpcodeFn)opHandler_JUMP3,
    /* 0x037  op025  LADDERUP        */ (OpcodeFn)opHandler_LADDERUP,
    /* 0x038  op026  LADDERDOWN      */ (OpcodeFn)opHandler_LADDERDOWN,
    /* 0x039  op027  LADDERUP2       */ (OpcodeFn)opHandler_LADDERUP2,
    /* 0x03A  op028  LADDERDOWN2     */ (OpcodeFn)opHandler_LADDERDOWN2,
    /* 0x03B  op029  MAPJUMP         */ (OpcodeFn)opHandler_MAPJUMP,
    /* 0x03C  op02A  MAPJUMP3        */ (OpcodeFn)opHandler_MAPJUMP3,
    /* 0x03D  op02B  SETMODEL        */ (OpcodeFn)opHandler_SETMODEL,
    /* 0x03E  op02C  BASEANIME       */ (OpcodeFn)opHandler_BASEANIME,
    /* 0x03F  op02D  ANIME           */ (OpcodeFn)opHandler_ANIME,
    /* 0x040  op02E  ANIMEKEEP       */ (OpcodeFn)opHandler_ANIMEKEEP,
    /* 0x041  op02F  CANIME          */ (OpcodeFn)opHandler_CANIME,
    /* 0x042  op030  CANIMEKEEP      */ (OpcodeFn)opHandler_CANIMEKEEP,
    /* 0x043  op031  RANIME          */ (OpcodeFn)opHandler_RANIME,
    /* 0x044  op032  RANIMEKEEP      */ (OpcodeFn)opHandler_RANIMEKEEP,
    /* 0x045  op033  RCANIME         */ (OpcodeFn)opHandler_RCANIME,
    /* 0x046  op034  RCANIMEKEEP     */ (OpcodeFn)opHandler_RCANIMEKEEP,
    /* 0x047  op035  RANIMELOOP      */ (OpcodeFn)opHandler_RANIMELOOP,
    /* 0x048  op036  RCANIMELOOP     */ (OpcodeFn)opHandler_RCANIMELOOP,
    /* 0x049  op037  LADDERANIME     */ (OpcodeFn)opHandler_LADDERANIME,
    /* 0x04A  op038  DISCJUMP        */ (OpcodeFn)opHandler_DISCJUMP,
    /* 0x04B  op039  SETLINE         */ (OpcodeFn)opHandler_SETLINE,
    /* 0x04C  op03A  LINEON          */ (OpcodeFn)opHandler_LINEON,
    /* 0x04D  op03B  LINEOFF         */ (OpcodeFn)opHandler_LINEOFF,
    /* 0x04E  op03C  WAIT            */ (OpcodeFn)opHandler_WAIT,
    /* 0x04F  op03D  MSPEED          */ (OpcodeFn)opHandler_MSPEED,
    /* 0x050  op03E  MOVE            */ (OpcodeFn)opHandler_MOVE,
    /* 0x051  op03F  MOVEA           */ (OpcodeFn)opHandler_MOVEA,
    /* 0x052  op040  PMOVEA          */ (OpcodeFn)opHandler_PMOVEA,
    /* 0x053  op041  CMOVE           */ (OpcodeFn)opHandler_CMOVE,
    /* 0x054  op042  FMOVE           */ (OpcodeFn)opHandler_FMOVE,
    /* 0x055  op043  PJUMPA          */ (OpcodeFn)opHandler_PJUMPA,
    /* 0x056  op044  ANIMESYNC       */ (OpcodeFn)opHandler_ANIMESYNC,
    /* 0x057  op045  ANIMESTOP       */ (OpcodeFn)opHandler_ANIMESTOP,
    /* 0x058  op046  MESW            */ (OpcodeFn)opHandler_MESW,
    /* 0x059  op047  MES             */ (OpcodeFn)opHandler_MES,
    /* 0x05A  op048  MESSYNC         */ (OpcodeFn)opHandler_MESSYNC,
    /* 0x05B  op049  MESVAR          */ (OpcodeFn)opHandler_MESVAR,
    /* 0x05C  op04A  ASK             */ (OpcodeFn)opHandler_ASK,
    /* 0x05D  op04B  WINSIZE         */ (OpcodeFn)opHandler_WINSIZE,
    /* 0x05E  op04C  WINCLOSE        */ (OpcodeFn)opHandler_WINCLOSE,
    /* 0x05F  op04D  UCON            */ (OpcodeFn)opHandler_UCON,
    /* 0x060  op04E  UCOFF           */ (OpcodeFn)opHandler_UCOFF,
    /* 0x061  op04F  MOVIE           */ (OpcodeFn)opHandler_MOVIE,
    /* 0x062  op050  MOVIESYNC       */ (OpcodeFn)opHandler_MOVIESYNC,
    /* 0x063  op051  SETPC           */ (OpcodeFn)opHandler_SETPC,
    /* 0x064  op052  DIR             */ (OpcodeFn)opHandler_DIR,
    /* 0x065  op053  DIRP            */ (OpcodeFn)opHandler_DIRP,
    /* 0x066  op054  DIRA            */ (OpcodeFn)opHandler_DIRA,
    /* 0x067  op055  PDIRA           */ (OpcodeFn)opHandler_PDIRA,
    /* 0x068  op056  SPUREADY        */ (OpcodeFn)opHandler_SPUREADY,
    /* 0x069  op057  TALKON          */ (OpcodeFn)func_800B0B04,
    /* 0x06A  op058  TALKOFF         */ (OpcodeFn)func_800B0B10,
    /* 0x06B  op059  PUSHON          */ (OpcodeFn)func_800B0B20,
    /* 0x06C  op05A  PUSHOFF         */ (OpcodeFn)func_800B0B2C,
    /* 0x06D  op05B  ISTOUCH         */ (OpcodeFn)func_800B0C64,
    /* 0x06E  op05C  MAPJUMPO        */ (OpcodeFn)opHandler_MAPJUMPO,
    /* 0x06F  op05D  MAPJUMPON       */ (OpcodeFn)opHandler_MAPJUMPON,
    /* 0x070  op05E  MAPJUMPOFF      */ (OpcodeFn)opHandler_MAPJUMPOFF,
    /* 0x071  op05F  SETMESSPEED     */ (OpcodeFn)opHandler_SETMESSPEED,
    /* 0x072  op060  SHOW            */ (OpcodeFn)func_800B0A08,
    /* 0x073  op061  HIDE            */ (OpcodeFn)func_800B0A7C,
    /* 0x074  op062  TALKRADIUS      */ (OpcodeFn)func_800B0CCC,
    /* 0x075  op063  PUSHRADIUS      */ (OpcodeFn)func_800B0CFC,
    /* 0x076  op064  AMESW           */ (OpcodeFn)opHandler_AMESW,
    /* 0x077  op065  AMES            */ (OpcodeFn)opHandler_AMES,
    /* 0x078  op066  GETINFO         */ (OpcodeFn)func_800B0D2C,
    /* 0x079  op067  THROUGHON       */ (OpcodeFn)func_800B0C48,
    /* 0x07A  op068  THROUGHOFF      */ (OpcodeFn)func_800B0C58,
    /* 0x07B  op069  BATTLE          */ (OpcodeFn)opHandler_BATTLE,
    /* 0x07C  op06A  BATTLERESULT    */ (OpcodeFn)opHandler_BATTLERESULT,
    /* 0x07D  op06B  BATTLEON        */ (OpcodeFn)opHandler_BATTLEON,
    /* 0x07E  op06C  BATTLEOFF       */ (OpcodeFn)opHandler_BATTLEOFF,
    /* 0x07F  op06D  KEYSCAN         */ (OpcodeFn)opHandler_KEYSCAN,
    /* 0x080  op06E  KEYON           */ (OpcodeFn)opHandler_KEYON,
    /* 0x081  op06F  AASK            */ (OpcodeFn)opHandler_AASK,
    /* 0x082  op070  PGETINFO        */ (OpcodeFn)opHandler_PGETINFO,
    /* 0x083  op071  DSCROLL         */ (OpcodeFn)opHandler_DSCROLL,
    /* 0x084  op072  LSCROLL         */ (OpcodeFn)opHandler_LSCROLL,
    /* 0x085  op073  CSCROLL         */ (OpcodeFn)opHandler_CSCROLL,
    /* 0x086  op074  DSCROLLA        */ (OpcodeFn)opHandler_DSCROLLA,
    /* 0x087  op075  LSCROLLA       */ (OpcodeFn)opHandler_LSCROLLA,
    /* 0x088  op076  CSCROLLA       */ (OpcodeFn)opHandler_CSCROLLA,
    /* 0x089  op077  SCROLLSYNC      */ (OpcodeFn)opHandler_SCROLLSYNC,
    /* 0x08A  op078  RMOVE          */ (OpcodeFn)opHandler_RMOVE,
    /* 0x08B  op079  RMOVEA         */ (OpcodeFn)opHandler_RMOVEA,
    /* 0x08C  op07A  RPMOVEA        */ (OpcodeFn)opHandler_RPMOVEA,
    /* 0x08D  op07B  RCMOVE         */ (OpcodeFn)opHandler_RCMOVE,
    /* 0x08E  op07C  RFMOVE         */ (OpcodeFn)opHandler_RFMOVE,
    /* 0x08F  op07D  MOVESYNC        */ (OpcodeFn)opHandler_MOVESYNC,
    /* 0x090  op07E  CLEAR           */ (OpcodeFn)opHandler_CLEAR,
    /* 0x091  op07F  DSCROLLP       */ (OpcodeFn)opHandler_DSCROLLP,
    /* 0x092  op080  LSCROLLP       */ (OpcodeFn)opHandler_LSCROLLP,
    /* 0x093  op081  CSCROLLP       */ (OpcodeFn)opHandler_CSCROLLP,
    /* 0x094  op082  LTURNR         */ (OpcodeFn)opHandler_LTURNR,
    /* 0x095  op083  LTURNL         */ (OpcodeFn)opHandler_LTURNL,
    /* 0x096  op084  CTURNR          */ (OpcodeFn)opHandler_CTURNR,
    /* 0x097  op085  CTURNL          */ (OpcodeFn)opHandler_CTURNL,
    /* 0x098  op086  ADDPARTY        */ (OpcodeFn)opHandler_ADDPARTY,
    /* 0x099  op087  SUBPARTY        */ (OpcodeFn)opHandler_SUBPARTY,
    /* 0x09A  op088  CHANGEPARTY    */ (OpcodeFn)func_800B002C,
    /* 0x09B  op089  REFRESHPARTY   */ (OpcodeFn)func_800B0280,
    /* 0x09C  op08A  SETPARTY        */ (OpcodeFn)opHandler_SETPARTY,
    /* 0x09D  op08B  ISPARTY         */ (OpcodeFn)opHandler_ISPARTY,
    /* 0x09E  op08C  ADDMEMBER       */ (OpcodeFn)opHandler_ADDMEMBER,
    /* 0x09F  op08D  SUBMEMBER       */ (OpcodeFn)opHandler_SUBMEMBER,
    /* 0x0A0  op08E  ISMEMBER       */ (OpcodeFn)func_800B0570,
    /* 0x0A1  op08F  LTURN          */ (OpcodeFn)opHandler_LTURN,
    /* 0x0A2  op090  CTURN           */ (OpcodeFn)opHandler_CTURN,
    /* 0x0A3  op091  PLTURN         */ (OpcodeFn)opHandler_PLTURN,
    /* 0x0A4  op092  PCTURN          */ (OpcodeFn)opHandler_PCTURN,
    /* 0x0A5  op093  JOIN            */ (OpcodeFn)opHandler_JOIN,
    /* 0x0A6  op094  MESFORCUS      */ (OpcodeFn)opHandler_MESFORCUS,
    /* 0x0A7  op095  BGANIME         */ (OpcodeFn)opHandler_BGANIME,
    /* 0x0A8  op096  RBGANIME       */ (OpcodeFn)opHandler_RBGANIME,
    /* 0x0A9  op097  RBGANIMELOOP   */ (OpcodeFn)opHandler_RBGANIMELOOP,
    /* 0x0AA  op098  BGANIMESYNC    */ (OpcodeFn)opHandler_BGANIMESYNC,
    /* 0x0AB  op099  BGDRAW         */ (OpcodeFn)opHandler_BGDRAW,
    /* 0x0AC  op09A  BGOFF          */ (OpcodeFn)opHandler_BGOFF,
    /* 0x0AD  op09B  BGANIMESPEED   */ (OpcodeFn)opHandler_BGANIMESPEED,
    /* 0x0AE  op09C  SETTIMER        */ (OpcodeFn)opHandler_SETTIMER,
    /* 0x0AF  op09D  DISPTIMER       */ (OpcodeFn)opHandler_DISPTIMER,
    /* 0x0B0  op09E  SHADETIMER     */ (OpcodeFn)opHandler_SHADETIMER,
    /* 0x0B1  op09F  SETGETA         */ (OpcodeFn)opHandler_SETGETA,
    /* 0x0B2  op0A0  SETROOTTRANS   */ (OpcodeFn)opHandler_SETROOTTRANS,
    /* 0x0B3  op0A1  SETVIBRATE      */ (OpcodeFn)opHandler_SETVIBRATE,
    /* 0x0B4  op0A2  STOPVIBRATE    */ (OpcodeFn)opHandler_STOPVIBRATE,
    /* 0x0B5  op0A3  MOVIEREADY      */ (OpcodeFn)opHandler_MOVIEREADY,
    /* 0x0B6  op0A4  GETTIMER       */ (OpcodeFn)opHandler_GETTIMER,
    /* 0x0B7  op0A5  FADEIN         */ (OpcodeFn)opHandler_FADEIN,
    /* 0x0B8  op0A6  FADEOUT        */ (OpcodeFn)opHandler_FADEOUT,
    /* 0x0B9  op0A7  FADESYNC       */ (OpcodeFn)opHandler_FADESYNC,
    /* 0x0BA  op0A8  SHAKE          */ (OpcodeFn)opHandler_SHAKE,
    /* 0x0BB  op0A9  SHAKEOFF       */ (OpcodeFn)opHandler_SHAKEOFF,
    /* 0x0BC  op0AA  FADEBLACK       */ (OpcodeFn)opHandler_FADEBLACK,
    /* 0x0BD  op0AB  FOLLOWOFF      */ (OpcodeFn)opHandler_FOLLOWOFF,
    /* 0x0BE  op0AC  FOLLOWON       */ (OpcodeFn)opHandler_FOLLOWON,
    /* 0x0BF  op0AD  GAMEOVER        */ (OpcodeFn)opHandler_GAMEOVER,
    /* 0x0C0  op0AE  ENDING         */ (OpcodeFn)opHandler_ENDING,
    /* 0x0C1  op0AF  SHADELEVEL      */ (OpcodeFn)opHandler_SHADELEVEL,
    /* 0x0C2  op0B0  SHADEFORM      */ (OpcodeFn)opHandler_SHADEFORM,
    /* 0x0C3  op0B1  FMOVEA         */ (OpcodeFn)opHandler_FMOVEA,
    /* 0x0C4  op0B2  FMOVEP         */ (OpcodeFn)opHandler_FMOVEP,
    /* 0x0C5  op0B3  SHADESET       */ (OpcodeFn)opHandler_SHADESET,
    /* 0x0C6  op0B4  MUSICCHANGE     */ (OpcodeFn)opHandler_MUSICCHANGE,
    /* 0x0C7  op0B5  MUSICLOAD       */ (OpcodeFn)opHandler_MUSICLOAD,
    /* 0x0C8  op0B6  FADENONE       */ (OpcodeFn)opHandler_FADENONE,
    /* 0x0C9  op0B7  POLYCOLOR      */ (OpcodeFn)opHandler_POLYCOLOR,
    /* 0x0CA  op0B8  POLYCOLORALL   */ (OpcodeFn)opHandler_POLYCOLORALL,
    /* 0x0CB  op0B9  KILLTIMER      */ (OpcodeFn)opHandler_KILLTIMER,
    /* 0x0CC  op0BA  CROSSMUSIC     */ (OpcodeFn)opHandler_CROSSMUSIC,
    /* 0x0CD  op0BB  DUALMUSIC      */ (OpcodeFn)opHandler_DUALMUSIC,
    /* 0x0CE  op0BC  EFFECTPLAY      */ (OpcodeFn)opHandler_EFFECTPLAY,
    /* 0x0CF  op0BD  EFFECTLOAD      */ (OpcodeFn)opHandler_EFFECTLOAD,
    /* 0x0D0  op0BE  LOADSYNC       */ (OpcodeFn)opHandler_LOADSYNC,
    /* 0x0D1  op0BF  MUSICSTOP       */ (OpcodeFn)opHandler_MUSICSTOP,
    /* 0x0D2  op0C0  MUSICVOL        */ (OpcodeFn)opHandler_MUSICVOL,
    /* 0x0D3  op0C1  MUSICVOLTRANS   */ (OpcodeFn)opHandler_MUSICVOLTRANS,
    /* 0x0D4  op0C2  MUSICVOLFADE   */ (OpcodeFn)opHandler_MUSICVOLFADE,
    /* 0x0D5  op0C3  ALLSEVOL        */ (OpcodeFn)opHandler_ALLSEVOL,
    /* 0x0D6  op0C4  ALLSEVOLTRANS   */ (OpcodeFn)opHandler_ALLSEVOLTRANS,
    /* 0x0D7  op0C5  ALLSEPOS        */ (OpcodeFn)opHandler_ALLSEPOS,
    /* 0x0D8  op0C6  ALLSEPOSTRANS   */ (OpcodeFn)opHandler_ALLSEPOSTRANS,
    /* 0x0D9  op0C7  SEVOL           */ (OpcodeFn)opHandler_SEVOL,
    /* 0x0DA  op0C8  SEVOLTRANS      */ (OpcodeFn)opHandler_SEVOLTRANS,
    /* 0x0DB  op0C9  SEPOS           */ (OpcodeFn)opHandler_SEPOS,
    /* 0x0DC  op0CA  SEPOSTRANS      */ (OpcodeFn)opHandler_SEPOSTRANS,
    /* 0x0DD  op0CB  SETBATTLEMUSIC  */ (OpcodeFn)opHandler_SETBATTLEMUSIC,
    /* 0x0DE  op0CC  BATTLEMODE      */ (OpcodeFn)opHandler_BATTLEMODE,
    /* 0x0DF  op0CD  SESTOP          */ (OpcodeFn)opHandler_SESTOP,
    /* 0x0E0  op0CE  BGANIMEFLAG    */ (OpcodeFn)opHandler_BGANIMEFLAG,
    /* 0x0E1  op0CF  INITSOUND      */ (OpcodeFn)opHandler_INITSOUND,
    /* 0x0E2  op0D0  BGSHADE        */ (OpcodeFn)opHandler_BGSHADE,
    /* 0x0E3  op0D1  BGSHADESTOP    */ (OpcodeFn)opHandler_BGSHADESTOP,
    /* 0x0E4  op0D2  RBGSHADELOOP   */ (OpcodeFn)opHandler_RBGSHADELOOP,
    /* 0x0E5  op0D3  DSCROLL2       */ (OpcodeFn)opHandler_DSCROLL2,
    /* 0x0E6  op0D4  LSCROLL2       */ (OpcodeFn)opHandler_LSCROLL2,
    /* 0x0E7  op0D5  CSCROLL2       */ (OpcodeFn)opHandler_CSCROLL2,
    /* 0x0E8  op0D6  DSCROLLA2      */ (OpcodeFn)opHandler_DSCROLLA2,
    /* 0x0E9  op0D7  LSCROLLA2      */ (OpcodeFn)opHandler_LSCROLLA2,
    /* 0x0EA  op0D8  CSCROLLA2      */ (OpcodeFn)opHandler_CSCROLLA2,
    /* 0x0EB  op0D9  DSCROLLP2      */ (OpcodeFn)opHandler_DSCROLLP2,
    /* 0x0EC  op0DA  LSCROLLP2      */ (OpcodeFn)opHandler_LSCROLLP2,
    /* 0x0ED  op0DB  CSCROLLP2      */ (OpcodeFn)opHandler_CSCROLLP2,
    /* 0x0EE  op0DC  SCROLLSYNC2    */ (OpcodeFn)opHandler_SCROLLSYNC2,
    /* 0x0EF  op0DD  SCROLLMODE2    */ (OpcodeFn)opHandler_SCROLLMODE2,
    /* 0x0F0  op0DE  MENUENABLE     */ (OpcodeFn)opHandler_MENUENABLE,
    /* 0x0F1  op0DF  MENUDISABLE    */ (OpcodeFn)opHandler_MENUDISABLE,
    /* 0x0F2  op0E0  FOOTSTEPON     */ (OpcodeFn)opHandler_FOOTSTEPON,
    /* 0x0F3  op0E1  FOOTSTEPOFF    */ (OpcodeFn)opHandler_FOOTSTEPOFF,
    /* 0x0F4  op0E2  FOOTSTEPOFFALL */ (OpcodeFn)opHandler_FOOTSTEPOFFALL,
    /* 0x0F5  op0E3  FOOTSTEPCUT    */ (OpcodeFn)opHandler_FOOTSTEPCUT,
    /* 0x0F6  op0E4  PREMAPJUMP     */ (OpcodeFn)opHandler_PREMAPJUMP,
    /* 0x0F7  op0E5  USE             */ (OpcodeFn)opHandler_USE,
    /* 0x0F8  op0E6  SPLIT           */ (OpcodeFn)opHandler_SPLIT,
    /* 0x0F9  op0E7  ANIMESPEED      */ (OpcodeFn)opHandler_ANIMESPEED,
    /* 0x0FA  op0E8  RND             */ (OpcodeFn)opHandler_RND,
    /* 0x0FB  op0E9  DCOLADD        */ (OpcodeFn)opHandler_DCOLADD,
    /* 0x0FC  op0EA  DCOLSUB        */ (OpcodeFn)opHandler_DCOLSUB,
    /* 0x0FD  op0EB  TCOLADD        */ (OpcodeFn)opHandler_TCOLADD,
    /* 0x0FE  op0EC  TCOLSUB        */ (OpcodeFn)opHandler_TCOLSUB,
    /* 0x0FF  op0ED  FCOLADD        */ (OpcodeFn)opHandler_FCOLADD,
    /* 0x100  op0EE  FCOLSUB         */ (OpcodeFn)opHandler_FCOLSUB,
    /* 0x101  op0EF  COLSYNC        */ (OpcodeFn)opHandler_COLSYNC,
    /* 0x102  op0F0  DOFFSET        */ (OpcodeFn)opHandler_DOFFSET,
    /* 0x103  op0F1  LOFFSETS       */ (OpcodeFn)opHandler_LOFFSETS,
    /* 0x104  op0F2  COFFSETS       */ (OpcodeFn)opHandler_COFFSETS,
    /* 0x105  op0F3  LOFFSET        */ (OpcodeFn)opHandler_LOFFSET,
    /* 0x106  op0F4  COFFSET        */ (OpcodeFn)opHandler_COFFSET,
    /* 0x107  op0F5  OFFSETSYNC     */ (OpcodeFn)opHandler_OFFSETSYNC,
    /* 0x108  op0F6  RUNENABLE       */ (OpcodeFn)opHandler_RUNENABLE,
    /* 0x109  op0F7  RUNDISABLE      */ (OpcodeFn)opHandler_RUNDISABLE,
    /* 0x10A  op0F8  MAPFADEOFF     */ (OpcodeFn)opHandler_MAPFADEOFF,
    /* 0x10B  op0F9  MAPFADEON      */ (OpcodeFn)opHandler_MAPFADEON,
    /* 0x10C  op0FA  INITTRACE      */ (OpcodeFn)opHandler_INITTRACE,
    /* 0x10D  op0FB  SETDRESS       */ (OpcodeFn)func_800AF120,
    /* 0x10E  op0FC  GETDRESS       */ (OpcodeFn)func_800AF1AC,
    /* 0x10F  op0FD  FACEDIR        */ (OpcodeFn)opHandler_FACEDIR,
    /* 0x110  op0FE  FACEDIRA        */ (OpcodeFn)opHandler_FACEDIRA,
    /* 0x111  op0FF  FACEDIRP        */ (OpcodeFn)opHandler_FACEDIRP,
    /* 0x112  op100  FACEDIRLIMIT    */ (OpcodeFn)opHandler_FACEDIRLIMIT,
    /* 0x113  op101  FACEDIROFF      */ (OpcodeFn)opHandler_FACEDIROFF,
    /* 0x114  op102  SARALYOFF       */ (OpcodeFn)opHandler_SARALYOFF,
    /* 0x115  op103  SARALYON        */ (OpcodeFn)opHandler_SARALYON,
    /* 0x116  op104  SARALYDISPOFF   */ (OpcodeFn)opHandler_SARALYDISPOFF,
    /* 0x117  op105  SARALYDISPON    */ (OpcodeFn)opHandler_SARALYDISPON,
    /* 0x118  op106  MESMODE         */ (OpcodeFn)opHandler_MESMODE,
    /* 0x119  op107  FACEDIRINIT     */ (OpcodeFn)opHandler_FACEDIRINIT,
    /* 0x11A  op108  FACEDIRI       */ (OpcodeFn)opHandler_FACEDIRI,
    /* 0x11B  op109  JUNCTION        */ (OpcodeFn)opHandler_JUNCTION,
    /* 0x11C  op10A  SETCAMERA      */ (OpcodeFn)opHandler_SETCAMERA,
    /* 0x11D  op10B  BATTLECUT       */ (OpcodeFn)opHandler_BATTLECUT,
    /* 0x11E  op10C  FOOTSTEPCOPY   */ (OpcodeFn)opHandler_FOOTSTEPCOPY,
    /* 0x11F  op10D  WORLDMAPJUMP    */ (OpcodeFn)opHandler_WORLDMAPJUMP,
    /* 0x120  op10E  RFACEDIRI      */ (OpcodeFn)opHandler_RFACEDIRI,
    /* 0x121  op10F  RFACEDIR       */ (OpcodeFn)opHandler_RFACEDIR,
    /* 0x122  op110  RFACEDIRA      */ (OpcodeFn)opHandler_RFACEDIRA,
    /* 0x123  op111  RFACEDIRP      */ (OpcodeFn)opHandler_RFACEDIRP,
    /* 0x124  op112  RFACEDIROFF    */ (OpcodeFn)opHandler_RFACEDIROFF,
    /* 0x125  op113  FACEDIRSYNC    */ (OpcodeFn)opHandler_FACEDIRSYNC,
    /* 0x126  op114  COPYINFO       */ (OpcodeFn)func_800B1034,
    /* 0x127  op115  PCOPYINFO      */ (OpcodeFn)func_800B10F8,
    /* 0x128  op116  RAMESW          */ (OpcodeFn)opHandler_RAMESW,
    /* 0x129  op117  BGSHADEOFF     */ (OpcodeFn)opHandler_BGSHADEOFF,
    /* 0x12A  op118  AXIS           */ (OpcodeFn)opHandler_AXIS,
    /* 0x12B  op119  AXISSYNC       */ (OpcodeFn)opHandler_AXISSYNC,
    /* 0x12C  op11A  MENUNORMAL      */ (OpcodeFn)opHandler_MENUNORMAL,
    /* 0x12D  op11B  MENUPHS         */ (OpcodeFn)opHandler_MENUPHS,
    /* 0x12E  op11C  BGCLEAR        */ (OpcodeFn)opHandler_BGCLEAR,
    /* 0x12F  op11D  GETPARTY        */ (OpcodeFn)opHandler_GETPARTY,
    /* 0x130  op11E  MENUSHOP        */ (OpcodeFn)opHandler_MENUSHOP,
    /* 0x131  op11F  DISC            */ (OpcodeFn)opHandler_DISC,
    /* 0x132  op120  DSCROLL3       */ (OpcodeFn)opHandler_DSCROLL3,
    /* 0x133  op121  LSCROLL3       */ (OpcodeFn)opHandler_LSCROLL3,
    /* 0x134  op122  CSCROLL3       */ (OpcodeFn)opHandler_CSCROLL3,
    /* 0x135  op123  MACCEL         */ (OpcodeFn)opHandler_MACCEL,
    /* 0x136  op124  MLIMIT         */ (OpcodeFn)opHandler_MLIMIT,
    /* 0x137  op125  ADDITEM         */ (OpcodeFn)opHandler_ADDITEM,
    /* 0x138  op126  SETWITCH        */ (OpcodeFn)opHandler_SETWITCH,
    /* 0x139  op127  SETODIN         */ (OpcodeFn)opHandler_SETODIN,
    /* 0x13A  op128  RESETGF        */ (OpcodeFn)func_800B08CC,
    /* 0x13B  op129  MENUNAME        */ (OpcodeFn)opHandler_MENUNAME,
    /* 0x13C  op12A  REST           */ (OpcodeFn)opHandler_REST,
    /* 0x13D  op12B  MOVECANCEL     */ (OpcodeFn)opHandler_MOVECANCEL,
    /* 0x13E  op12C  PMOVECANCEL    */ (OpcodeFn)opHandler_PMOVECANCEL,
    /* 0x13F  op12D  ACTORMODE       */ (OpcodeFn)opHandler_ACTORMODE,
    /* 0x140  op12E  MENUSAVE        */ (OpcodeFn)opHandler_MENUSAVE,
    /* 0x141  op12F  SAVEENABLE      */ (OpcodeFn)opHandler_SAVEENABLE,
    /* 0x142  op130  PHSENABLE       */ (OpcodeFn)opHandler_PHSENABLE,
    /* 0x143  op131  HOLD            */ (OpcodeFn)opHandler_HOLD,
    /* 0x144  op132  MOVIECUT        */ (OpcodeFn)func_800B1730,
    /* 0x145  op133  SETPLACE        */ (OpcodeFn)opHandler_SETPLACE,
    /* 0x146  op134  SETDCAMERA     */ (OpcodeFn)opHandler_SETDCAMERA,
    /* 0x147  op135  CHOICEMUSIC    */ (OpcodeFn)opHandler_CHOICEMUSIC,
    /* 0x148  op136  GETCARD        */ (OpcodeFn)opHandler_GETCARD,
    /* 0x149  op137  DRAWPOINT       */ (OpcodeFn)opHandler_DRAWPOINT,
    /* 0x14A  op138  PHSPOWER        */ (OpcodeFn)opHandler_PHSPOWER,
    /* 0x14B  op139  KEY            */ (OpcodeFn)func_800AFD20,
    /* 0x14C  op13A  CARDGAME        */ (OpcodeFn)opHandler_CARDGAME,
    /* 0x14D  op13B  SETBAR         */ (OpcodeFn)opHandler_SETBAR,
    /* 0x14E  op13C  DISPBAR        */ (OpcodeFn)opHandler_DISPBAR,
    /* 0x14F  op13D  KILLBAR        */ (OpcodeFn)opHandler_KILLBAR,
    /* 0x150  op13E  SCROLLRATIO2   */ (OpcodeFn)opHandler_SCROLLRATIO2,
    /* 0x151  op13F  WHOAMI          */ (OpcodeFn)func_800B0E68,
    /* 0x152  op140  MUSICSTATUS    */ (OpcodeFn)opHandler_MUSICSTATUS,
    /* 0x153  op141  MUSICREPLAY    */ (OpcodeFn)opHandler_MUSICREPLAY,
    /* 0x154  op142  DOORLINEOFF    */ (OpcodeFn)func_800AF5D4,
    /* 0x155  op143  DOORLINEON     */ (OpcodeFn)func_800AF5C4,
    /* 0x156  op144  MUSICSKIP      */ (OpcodeFn)opHandler_MUSICSKIP,
    /* 0x157  op145  DYING           */ (OpcodeFn)opHandler_DYING,
    /* 0x158  op146  SETHP          */ (OpcodeFn)opHandler_SETHP,
    /* 0x159  op147  GETHP          */ (OpcodeFn)opHandler_GETHP,
    /* 0x15A  op148  MOVEFLUSH       */ (OpcodeFn)opHandler_MOVEFLUSH,
    /* 0x15B  op149  MUSICVOLSYNC   */ (OpcodeFn)opHandler_MUSICVOLSYNC,
    /* 0x15C  op14A  PUSHANIME      */ (OpcodeFn)opHandler_PUSHANIME,
    /* 0x15D  op14B  POPANIME       */ (OpcodeFn)opHandler_POPANIME,
    /* 0x15E  op14C  KEYSCAN2       */ (OpcodeFn)func_800AF364,
    /* 0x15F  op14D  KEYON2         */ (OpcodeFn)func_800AF3B4,
    /* 0x160  op14E  PARTICLEON     */ (OpcodeFn)opHandler_PARTICLEON,
    /* 0x161  op14F  PARTICLEOFF    */ (OpcodeFn)opHandler_PARTICLEOFF,
    /* 0x162  op150  KEYSIGHNCHANGE  */ (OpcodeFn)func_800B1DF4,
    /* 0x163  op151  ADDGIL         */ (OpcodeFn)opHandler_ADDGIL,
    /* 0x164  op152  ADDPASTGIL     */ (OpcodeFn)opHandler_ADDPASTGIL,
    /* 0x165  op153  ADDSEEDLEVEL    */ (OpcodeFn)opHandler_ADDSEEDLEVEL,
    /* 0x166  op154  PARTICLESET    */ (OpcodeFn)opHandler_PARTICLESET,
    /* 0x167  op155  SETDRAWPOINT    */ (OpcodeFn)opHandler_SETDRAWPOINT,
    /* 0x168  op156  MENUTIPS       */ (OpcodeFn)opHandler_MENUTIPS,
    /* 0x169  op157  LASTIN          */ (OpcodeFn)opHandler_LASTIN,
    /* 0x16A  op158  LASTOUT         */ (OpcodeFn)opHandler_LASTOUT,
    /* 0x16B  op159  SEALEDOFF       */ (OpcodeFn)opHandler_SEALEDOFF,
    /* 0x16C  op15A  MENUTUTO       */ (OpcodeFn)opHandler_MENUTUTO,
    /* 0x16D  op15B  OPENEYES       */ (OpcodeFn)opHandler_OPENEYES,
    /* 0x16E  op15C  CLOSEEYES      */ (OpcodeFn)opHandler_CLOSEEYES,
    /* 0x16F  op15D  BLINKEYES      */ (OpcodeFn)opHandler_BLINKEYES,
    /* 0x170  op15E  SETCARD         */ (OpcodeFn)opHandler_SETCARD,
    /* 0x171  op15F  HOWMANYCARD    */ (OpcodeFn)opHandler_HOWMANYCARD,
    /* 0x172  op160  WHERECARD      */ (OpcodeFn)opHandler_WHERECARD,
    /* 0x173  op161  ADDMAGIC        */ (OpcodeFn)opHandler_ADDMAGIC,
    /* 0x174  op162  SWAP           */ (OpcodeFn)func_800B06D0,
    /* 0x175  op163  SETPARTY2      */ (OpcodeFn)func_800B0638,
    /* 0x176  op164  SPUSYNC         */ (OpcodeFn)opHandler_SPUSYNC,
    /* 0x177  op165  BROKEN         */ (OpcodeFn)opHandler_BROKEN,
    /* 0x178  op166  DISABLEANGELO   */ (OpcodeFn)opHandler_DISABLEANGELO,
    /* 0x179  op167  ???             */ (OpcodeFn)func_800BD2AC,
    /* 0x17A  op168  ???             */ (OpcodeFn)func_800BD318,
    /* 0x17B  op169  UNKNOWN4        */ (OpcodeFn)func_800B9000,
    /* 0x17C  op16A  ???             */ (OpcodeFn)func_800B5134,
    /* 0x17D  op16B  ???             */ (OpcodeFn)func_800BA120,
    /* 0x17E  op16C  ???             */ (OpcodeFn)func_800BA1D0,
    /* 0x17F  op16D  ???             */ (OpcodeFn)func_800BA280,
    /* 0x180  op16E  ???             */ (OpcodeFn)func_800BA330,
    /* 0x181  op16F  ???             */ (OpcodeFn)func_800B1F04,
    /* 0x182  op170  HASITEM         */ (OpcodeFn)opHandler_HASITEM,
    /* 0x183  op171  CLOCKWISETURN  */ (OpcodeFn)opHandler_CLOCKWISETURN,
    /* 0x184  op172  COUNTERCLOCKWISETURN*/ (OpcodeFn)opHandler_COUNTERCLOCKWISETURN,
    /* 0x185  op173  CLOCKWISETURN2 */ (OpcodeFn)opHandler_CLOCKWISETURN2,
    /* 0x186  op174  COUNTERCLOCKWISETURN2*/ (OpcodeFn)func_800B85C8,
    /* 0x187  op175  UNKNOWN10       */ (OpcodeFn)func_800B629C,
};
